### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by skeith** [kamikat/bilibili-get#3]
I just installed and tried to run `bilibili-get` and I got this error

```
user@host:/home/tmp# bilibili-get https://www.bilibili.com/video/av22216245 -l
/usr/local/lib/node_modules/bilibili-get/lib/index.js:25
          .map(v => ({ ...location, ...info, ...v }))
                       ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/bilibili-get/bin/bilibili-get:8:16)
    at Module._compile (module.js:570:32)
```

how can I fix this?
here is my system information
```
user@host:/home/tmp# npm -v && node -v
3.10.8
v6.9.0
```

**Comment by kamikat** [comment]
The script uses ES6 parameter spreading syntax which works only for Node.js > 9.0.

**Comment by skeith** [comment]
Okay, so I installed node 9.11.1 and I got this now

```
user@host:/home/web/get# bilibili-get https://www.bilibili.com/video/av22216245 -q 116
extracting video metadata...
[1/1] av22216245: start download "【KEYABINGO！4】EP01恶搞躲避球【真的假字幕组】"...
[1/1] av22216245: video quality:
[1/1] av22216245:     116     flv_p60        高清 1080P60
[1/1] av22216245:     74      flv720_p60     高清 720P60
[1/1] av22216245:   * 80      flv            高清 1080P
[1/1] av22216245:     64      flv720         高清 720P
[1/1] av22216245:     32      flv480         清晰 480P
[1/1] av22216245:     15      flv360         流畅 360P
[1/1] av22216245: output format: flv
[1/1] av22216245: output path:
[1/1] av22216245:     /home/web/get/av22216245 【KEYABINGO！4】EP01恶搞躲避球【真的假字幕组】(1).flv
[1/1] av22216245: downloading video segment 1/4...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full'
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced
ERROR: download command failed with code 28.
```

that option is not shown when I do `bilibili-get --help`
adding `--download-result=full` is still giving the same error

**Comment by kamikat** [comment]
Errrrrr… this is an option supported by aria2 > 1.23.0 (the latest release is 1.33.1).

**Comment by skeith** [comment]
I see,
I uses aria2c from `apt install aria2` which give me `aria2 version 1.19.0`

I'll try manually compiling aria2

**Comment by kamikat** [comment]
Or you can try some PPA source 😺

**Comment by skeith** [comment]
~~already midway compiling and I don't know how to find PPA source for it~~

building failed, adding PPA then surprisingly xenial now list aria2c 1.32
I guess I am not the sharpest tool in the shed
